name: Renovate
on:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted. This should be every 15 minutes to start testing
    - cron: '0/15 * * * *'
  push:
    branches:
      - main
    paths:
      - ".github/renovate-config.json"
      - ".github/workflows/renovate.yml"
      - "renovate.json"
      - "scripts/**"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: tibdex/github-app-token@v2.1.0
        with:
          private_key: ${{ secrets.PRIVATE_KEY }}
          app_id: ${{ secrets.APP_ID }}

      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.2.2
        with:
          token: '${{ steps.get_token.outputs.token }}'
          configurationFile: .github/renovate-config.json
